### ISSUE TITLE
After the support library installed, /system/app/pm will be restore.

### ISSUE THREAD

**Issue by LoVaLo** [wDCat/ANRC#58]
Not sure if this is even an issue, but when I tried to install ANRC, I got the message, "After the support library installed, /system/app/pm will be restore." with no method to close it. Does this mean that ANRC is safely installed, and I can manually exit out, or does it mean that it is currently installing and I should wait?

**Comment by Ankush-p** [comment]
I experienced this as well. It turns out that there is an invisible button in the bottom right hand Connor of the dialogue. If you hold down on it (and your on 5.0+) you can actually see the material design animation. Clicking the button will close the dialogue, so I assume it means it the installation is finished.

**Comment by LoVaLo** [comment]
Well, the general UI of ANRC appears to be working, but I encountered another issue whilst trying to use it with Fate/grand order. I'll close this one and post another.
